Feat/experiment_manager
codecentric-oss/niceml-dashboard pull request #10
Opened 2024-04-25 10:36 UTC by ihsanKisi

## 📥 Pull Request Description

This pull request implements the experiment manager feature. This feature was requested to be able to filter experiments based on their properties.

## 👀 Affected Areas

Experiments

## 📝 Checklist

Please make sure you've completed the following tasks before submitting this pull request:

- [x] Pre-commit hooks were executed
- [ ] Changes have been reviewed by at least one other developer
- [x] Tests have been added or updated to cover the changes (only necessary if the changes affect the executable code)
- [ ] All tests ran successfully
- [ ] All merge conflicts are resolved
- [ ] Documentation has been updated to reflect the changes
- [ ] Any necessary migrations have been run

## 📌 Related Issues

[Feature]: We have to manage the experiments in the dashboard. #2

## 🔗 Links

Please provide any relevant links (e.g. documentation, external resources) that support your changes.

## 📷 Screenshots

Without filtering (10 experiments):
<img width="833" alt="image" src="https://github.com/codecentric-oss/niceml-dashboard/assets/114022183/5f19254c-b65e-4e1d-b67c-3803f9b0f437">

With filtering by experiment_type:
<img width="824" alt="image" src="https://github.com/codecentric-oss/niceml-dashboard/assets/114022183/e4776f29-0ff2-46a0-a8ea-3eee901570c1">

2024-04-25 11:38 UTC, aiakide requested changes
Please merge the current  `develop` branch. Please pay attention to which files you commit. Not everything should be added to the repo.

2024-04-29 08:40 UTC, Jankeyy approved these changes

2024-05-24 08:49 UTC, aiakide requested changes
Please have a look at the comments. We can talk about it again.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/State/State.py
> +    _observable_dicts: dict[StateKeys, ObservableDict]
Please use a more appropriate variable name than `_observable_dicts`. This is the data that is stored in our AppState.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/State/State.py
>  class EventManager:
Please use a more appropriate class name. This is where our app data is stored. I qould suggest something like `State`, or `AppState`.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/State/State.py
>          logger.debug("Event Manager cannot be initialized in a background task")
Is this a critical message? Then please use logger.warn. debug is probably rarely used as a log level.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/State/State.py
Please rename the package. In Python, it is common to name packages in lowercase letters. 
The file name should be the same as the name you have chosen for the class. Currently still `EventManager`.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/basecomponents/sidebar.py
> +    _get_event_manager,
Variable and method names begin with an underscore if they are to be declared as private. However, as you are importing the method here, it is no longer private. Please remove the leading underscore

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/basecomponents/sidebar.py
> +            button_callback = lambda e, et=experiment_type: (
That looks a bit hacky. Maybe you can implement a new button in `buttons.py` (`SidebarButton`) that has a `StateManager` and overrides the `on_click` method. The button also gets an `ExperimentType` when it is initialised. The for loop then initialises a button for each `ExperimentType`.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/basecomponents/sidebar.py
> +def on_stage_change(observable_dict: ObservableDict, value: str):
See the comment above. I don't think we need the method any more

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/basecomponents/sidebar.py
> +def get_enum(experiment_type: ExperimentType):
See the comment above. I don't think we need the method any more

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/basecomponents/sidebar.py
> +            button_callback = lambda e, et=experiment_type: (
We will probably get more button classes. Please make a package of the file `buttons.py` and create a separate module / file for each button.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/experiment/experiment_manager.py
> +        Filters the experiment list after filtering with the provided filters
Please use google-style docstrings

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/experiment/experiment_manager.py
> +        for key, value in filters.items():
Can you find better names than `key` and `value`?

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/experiment/experiment_manager.py
> +                if isinstance(value, dict):
I find this confusing, I would expect `filter` to be used as follows. 

experiment_manager.filter(experiment_id="abs233", git_version": "0.0.1: asdasd, 0.0.2: dasdad").

Therefore value is never a dict. Probably only `str`, `int`, `float`, `bool`. Other filters can be added later.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/experiment/experiment_manager.py
> +            except TypeError as e:
Please create your own exception that can inherit from TypeError. Maybe something like `ExperimentFilterError`.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/pages/home.py
> +    exp_dict = _instance.get_dict(ExperimentStateKeys.EXPERIMENT_DICT)
Rename `exp_dict` into something like `experiment_state` oder `experiment_data`

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/pages/home.py
> +    exp_dict.on_change(_experiment_runs_table.refresh)
I don't think experiment_runs_table should be declared as private with a leading underscore.

2024-05-24 08:49 UTC, aiakide commented on nicemldashboard/pages/home.py
> +def _experiment_runs_table(
Please move this method in `table.py`

2024-05-24 08:49 UTC, aiakide commented on pyproject.toml
> +ignore = ["E731"]
This rule makes sense. Lamdas are generally more difficult to read and should be avoided if possible.

2024-05-24 08:49 UTC, aiakide commented on tests/unit/nicemldashboard/experiment/test_experiment_manager.py
> +    non_filtered_experiments = [exp for exp in experiments if exp.name != name_to_test]
Why is the filtered experiment no longer included in the `experiments`? The filter method should only return the filtered experiment(s), but should not be removed from the list of experiments.

2024-05-24 08:49 UTC, aiakide commented on tests/unit/nicemldashboard/experiment/test_experiment_manager.py
> +    assert all(exp.experiment_id != id_to_test for exp in non_filtered_experiments)
Same here

2024-05-24 08:49 UTC, aiakide commented on tests/unit/nicemldashboard/experiment/test_experiment_manager.py
> +    assert all(
Same here

2024-05-24 08:49 UTC, aiakide commented on tests/unit/nicemldashboard/experiment/test_experiment_manager.py
> +    experiments_not_filtered = [exp for exp in experiments if exp not in filtered]
Same here

2024-05-24 08:49 UTC, aiakide commented on tests/unit/nicemldashboard/experiment/test_experiment_manager.py
> +    experiments_not_filtered = [exp for exp in experiments if exp not in filtered]
Same here

2024-05-24 11:38 UTC, aiakide commented on nicemldashboard/experiment/experiment_manager.py
Please remove underscore from filename

2024-05-28 10:31 UTC, aiakide approved these changes

2024-05-28 10:34 UTC, merged